name: Example Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a script using secrets
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
      run: |
        echo "The secret is $MY_SECRET"
